services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.7.1
    container_name: oauth2-proxy
    restart: unless-stopped
    ports:
      - 4180
    command:
      - --provider=oidc
      - --oidc-issuer-url=https://sso.local/realms/portal
      - --client-id=portal
      - --code-challenge-method=S256
      - --client-secret=secret
      - --cookie-secret=A7OAbNZF6VvcdJGqkHmo8xXY5p24u45wByGYgmWyWwo=
      - --email-domain=*
      - --upstream=http://tyk-gateway:8080
      - --http-address=0.0.0.0:4180
      - --pass-access-token=false
      - --set-authorization-header=true
      - --pass-authorization-header=true
      - --pass-user-headers=true
      - --set-xauthrequest=true
      - --session-store-type=redis
      - --redis-connection-url=redis://tyk-redis:6379/0
      - --skip-auth-preflight=true
      - --skip-provider-button=true
      - --cookie-secure=true
      - --cookie-refresh=5m
      - --cookie-expire=10m
      - --provider-ca-file=/etc/oauth2-proxy/certs/ca.crt

    volumes:
      - ../certs/ca:/etc/oauth2-proxy/certs:ro

    networks:
      - tyk
