TYK_MDCB_SECURITY_SECRET=hello
TYK_MDCB_STORAGE_ADDRS=tyk-redis:6379
TYK_MDCB_ANALYTICSCONFIG_MONGOURL=mongodb://tyk-mongo:27017/tyk_analytics
TYK_MDCB_LOGLEVEL=info
TYK_MDCB_FORWARDANALYTICSTOPUMP=false
TYK_MDCB_ANALYTICSCONFIG_TYPE=mongo
TYK_MDCB_LISTENPORT=9090
TYK_MDCB_HTTPSERVEROPTIONS_USESSL=false
TYK_MDCB_SECURITY_ENABLEHTTPSECUREENDPOINTS=true
TYK_MDCB_SERVEROPTIONS_USESSL=false