TYK_GW_USEREDISLOG=true
TYK_GW_TEMPLATEPATH=./templates
TYK_GW_HTTPSERVEROPTIONS_ENABLEPATHSUFFIXMATCHING=true
TYK_GW_STORAGE_TYPE=redis
TYK_GW_ANALYTICSCONFIG_TYPE=rpc
TYK_GW_LOCALSESSIONCACHE_DISABLECACHESESSIONSTATE=true
TYK_GW_SLAVEOPTIONS_RPCKEY=691a31658e93bd00016f3af3
TYK_GW_HASHKEYS=true
TYK_GW_POLICIES_POLICYSOURCE=rpc
TYK_GW_MIDDLEWAREPATH=./middleware
TYK_GW_ENFORCEORGDATAAGE=true
TYK_GW_ENABLEJSVM=true
TYK_GW_POLICIES_POLICYRECORDNAME=tyk_policies
TYK_GW_UPTIMETESTS_DISABLE=false
TYK_GW_PIDFILELOCATION=./tyk-gateway.pid
TYK_GW_STORAGE_DATABASE=1
TYK_GW_ENABLECUSTOMDOMAINS=true
TYK_GW_OAUTHREDIRECTURISEPARATOR=;
TYK_GW_LOGLEVEL=debug
TYK_GW_SECRET=352d20ee67be67f6340b4c0605b044b7
TYK_GW_ENABLEANALYTICS=true
TYK_GW_COPROCESSOPTIONS_COPROCESSGRPCSERVER=tcp://localhost:5555
TYK_GW_ALLOWINSECURECONFIGS=true
TYK_GW_SLAVEOPTIONS_USERPC=true
TYK_GW_SLAVEOPTIONS_GROUPID=687a64bbcd28f000015d2514
TYK_GW_SLAVEOPTIONS_USESSL=false
TYK_GW_STORAGE_MAXACTIVE=5000
TYK_GW_SLAVEOPTIONS_CONNECTIONSTRING=tyk-mdcb:9090
TYK_GW_USEDBAPPCONFIGS=false
TYK_GW_MAXIDLECONNSPERHOST=500
TYK_GW_SLAVEOPTIONS_SSLINSECURESKIPVERIFY=true
TYK_GW_UPTIMETESTS_CONFIG_FAILURETRIGGERSAMPLESIZE=3
TYK_GW_ENABLENONTRANSACTIONALRATELIMITER=true
TYK_GW_APPPATH=./test_apps/
TYK_GW_LISTENPORT=8080
TYK_GW_HTTPSERVEROPTIONS_ENABLEWEBSOCKETS=true
TYK_GW_STORAGE_ADDRS=tyk-redis:6379
TYK_GW_SLAVEOPTIONS_APIKEY=68c88e8faf2440e86bf94413d1cb2f9f
TYK_GW_UPTIMETESTS_CONFIG_CHECKERPOOLSIZE=50
TYK_GW_ENFORCEORGQUOTAS=true
TYK_GW_STORAGE_MAXIDLE=3000
TYK_GW_ENABLEHASHEDKEYSLISTING=true
TYK_GW_UPTIMETESTS_CONFIG_ENABLEUPTIMEANALYTICS=true
TYK_GW_UPTIMETESTS_CONFIG_TIMEWAIT=10
TYK_GW_ALLOWREMOTECONFIG=true
TYK_GW_TYKJSPATH=./js/tyk.js
TYK_GW_HASHKEYFUNCTION=murmur128